export const SET_OPERAND = 'SET_OPERAND';
export const SET_OPERATION = 'SET_OPERATION';
export const CLEAR_DATA = 'CLEAR_DATA';
export const TOGGLE_HISTORY = 'TOGGLE_HISTORY';
export const COMPLETE_CALCULATION = 'COMPLETE_CALCULATION';
